site_name: DataPoint for Python
theme: readthedocs
pages:
- [index.md, Main]
- [getting-started.md, "Getting Started"]
- [objects/index.md, "Objects", "Manager"]
- [objects/manager.md, "Objects", "Manager"]
- [objects/site.md, "Objects", "Site"]
- [objects/forecast.md, "Objects", "Forecast"]
- [objects/day.md, "Objects", "Day"]
- [objects/timestep.md, "Objects", "Timestep"]
- [objects/element.md, "Objects", "Element"]
