site_name: DataPoint for Python
pages:
- [index.md, Main]
- [getting-started.md, Getting Started]
- [objects/manager.md, Object - Manager]
- [objects/site.md, Object - Site]
- [objects/forecast.md, Object - Forecast]
- [objects/day.md, Object - Day]
- [objects/timestep.md, Object - Timestep]
- [objects/element.md, Object - Element]
